# Generated by Django 3.0.6 on 2020-05-23 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100, verbose_name='Категория')),
                ('price', models.PositiveIntegerField(verbose_name='Цена')),
            ],
        ),
    ]
