# Generated by Django 3.0.6 on 2020-06-13 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20200612_1954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='img',
            field=models.ImageField(default='noimg', upload_to='img', verbose_name='Картинка'),
        ),
    ]
