# Generated by Django 3.0.7 on 2020-06-13 18:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20200613_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 13, 18, 53, 33, 34393, tzinfo=utc), verbose_name='Дата публикации'),
        ),
        migrations.AlterField(
            model_name='building',
            name='img',
            field=models.ImageField(default='img/noimg.jpg', upload_to='img', verbose_name='Картинка'),
        ),
    ]
